apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  gnb-template.yml: |
      amf:
        addr: ${AMF_ADDR}                  # The address or hostname of the AMF.
        bind_addr: ${AMF_BIND_ADDR}             # A local IP that the gNB binds to for traffic from the AMF.

      ru_sdr:
        device_driver: {{ .Values.config.ru_sdr.device_driver }}                                               # The RF driver name.
        device_args: {{ .Values.config.ru_sdr.device_args }}     # Optionally pass arguments to the selected RF driver.
        srate: {{ .Values.config.ru_sdr.srate }}
        tx_gain: {{ .Values.config.ru_sdr.tx_gain }}                     # Transmit gain of the RF might need to adjusted to the given situation.
        rx_gain: {{ .Values.config.ru_sdr.rx_gain }}                       # Receive gain of the RF might need to adjusted to the given situation.

      cell_cfg:
        dl_arfcn: {{ .Values.config.cell_cfg.dl_arfcn }}                  # ARFCN of the downlink carrier (center frequency).
        band: {{ .Values.config.cell_cfg.band }}                           # The NR band.
        channel_bandwidth_MHz: {{ .Values.config.cell_cfg.channel_bandwidth_MHz }}          # Bandwith in MHz. Number of PRBs will be automatically derived.
        common_scs: {{ .Values.config.cell_cfg.common_scs }}                    # Subcarrier spacing in kHz used for data.
        plmn: {{ .Values.config.cell_cfg.plmn }}                   # PLMN broadcasted by the gNB.
        tac: {{ .Values.config.cell_cfg.tac }}                            # Tracking area code (needs to match the core configuration).
        pdcch:
          common:
            ss0_index: 0                  # Set search space zero index to match srsUE capabilities
            coreset0_index: 12            # Set search CORESET Zero index to match srsUE capabilities
          dedicated:
            ss2_type: common              # Search Space type, has to be set to common
            dci_format_0_1_and_1_1: false # Set correct DCI format (fallback)
        prach:
          prach_config_index: 1           # Sets PRACH config to match what is expected by srsUE      

      cu_cp:
        inactivity_timer: 7200            # Sets the UE/PDU Session/DRB inactivity timer to 7200 seconds. Supported: [1 - 7200].

      slicing:
        -
          sst: {{ .Values.config.sst}}
          sd: {{ .Values.config.sd}}

      log:
        filename: ./gnb.log            # Path of the log file.
        all_level: debug                   # Logging level applied to all layers.

      pcap:
        mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
        mac_filename: ./gnb_mac.pcap   # Path where the MAC PCAP is stored.
        ngap_enable: false                # Set to true to enable NGAP PCAPs.
        ngap_filename: ./gnb_ngap.pcap # Path where the NGAP PCAP is stored.

      e2:
        enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
        e2sm_kpm_enabled: true            # Enable KPM service module
        e2sm_rc_enabled: true             # Enable KPM service module
        addr: {{ .Values.config.e2.addr }}                  # RIC IP address
        bind_addr: ${AMF_BIND_ADDR}                # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
        port: {{ .Values.config.e2.port }}                       # RIC port