apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nonrtric-ingress
  namespace: nonrtric
spec:
  ingressClassName: nginx
  rules:
  - host: "nonrtric.bmw.lab"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: controlpanel
            port:
              number: 8080